/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mamashai.emoji;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import ti.modules.titanium.ui.widget.TiUILabel;
import android.widget.TextView;
import org.appcelerator.titanium.util.TiRHelper;
import android.app.Activity;

@Kroll.proxy(name = "Label", creatableInModule=EmojiModule.class, propertyAccessors = {
	TiC.PROPERTY_AUTO_LINK,
	//TiC.PROPERTY_ATTRIBUTED_STRING,
	TiC.PROPERTY_COLOR,
	TiC.PROPERTY_ELLIPSIZE,
	TiC.PROPERTY_FONT,
	TiC.PROPERTY_HIGHLIGHTED_COLOR,
	TiC.PROPERTY_HTML,
	TiC.PROPERTY_TEXT,
	TiC.PROPERTY_TEXT_ALIGN,
	TiC.PROPERTY_TEXTID,
	TiC.PROPERTY_WORD_WRAP,
	TiC.PROPERTY_VERTICAL_ALIGN,
	//TiC.PROPERTY_SHADOW_OFFSET,
	//TiC.PROPERTY_SHADOW_COLOR,
	//TiC.PROPERTY_SHADOW_RADIUS,
	//TiC.PROPERTY_INCLUDE_FONT_PADDING
})
public class EmojiLabelProxy extends TiViewProxy
{
	// Standard Debugging variables
	private static final String LCAT = "LabelProxy";
	private static final boolean DBG = TiConfig.LOGD;
	
	private int    m_fontsize = 0;
	
	public EmojiLabelView m_view;

	private class EmojiLabelView extends TiUILabel
	{
		public EmojiconTextView m_view;
		
		public EmojiLabelView(TiViewProxy proxy) {
			super(proxy);
			
			m_view = new EmojiconTextView(proxy.getActivity());
			setNativeView(m_view);
		}

		@Override
		public void processProperties(KrollDict d)
		{
			super.processProperties(d);
		}
	}


	// Constructor
	public EmojiLabelProxy()
	{
		super();
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		m_view = new EmojiLabelView(this);
		
		if (m_fontsize > 0){
			m_view.m_view.setEmojiconSize(m_fontsize);
		}
		return m_view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options)
	{
		super.handleCreationDict(options);

		if (options.containsKey("font") && options.getKrollDict("font").containsKey("fontSize")){
			int fontSize = options.getKrollDict("font").getInt("fontSize");
			m_fontsize = fontSize;
		}
	}
}